MainEvent = "MainEvent"
AudioEvent = "AudioChunk"
AudioRecorderFinished = "AudioRecorderFinished"
TranscriptionChanged = "TranscriptionChanged"
TranscriptionFinished = "TranscriptionFinished"
SummaryFinished = "SummaryFinished"
